### PR TITLE
Fix Html render into a Panel

### PR DESCRIPTION
**Pull request by khchine5**

### CODE REVIEW

**Comment by lsaffre** [comment]
Hamza, why did you restore "elems.py"?
Luc

**Comment by khchine5** [comment]
I had a merge conflict with your version but I have chosen to use  your version.
One more thing, lino_extjs6 is broken due that in "ext_render.py" there are use of 'lino.modlib.extjs.elems' classes. I am working on it.

**Comment by lsaffre** [comment]
You must just import them from lino.modlib.extjs.elems now. These two
files were the same before, and it makes no sense to have two versions.

**Comment by khchine5** [comment]
But for extjs6 , I have changed many definitions on elems.py and if I still use lino.modlib.extjs.elems , I got js errors.

**Comment by lsaffre** [comment]
Oops, you are right. I did not look well enough and thought that there
were no changes. Yes, sorry, I am guilty for this mess.

So one of us two must now adapt the new elems.py in a similar way as I
did for the old elems.py. I can do it, because it is not trivial, and I
did not explain very much the details of my changes. Or do you prefer to
try it yourself?

Luc

**Comment by khchine5** [comment]
No problem.
Let's do it like you have suggested by inheriting needed classes for lino_extjs6 project.

**Pull request merged**
